name: Deploy to Amplify

on:
  push:
    branches: ["main", "release"]
  workflow_dispatch:

env:
  APP_NAME: ${{ vars.APP_NAME }}
  ARTIFACT_FILE_NAME: ${{ vars.ARTIFACT_FILE_NAME }}
  ARTIFACT_S3_PATH: ${{ vars.ARTIFACT_S3_PATH }}
  APP_ID: ${{ vars.APP_ID }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: "18.18.x"
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependency
        run: npm install

      - name: Build
        run: npm run build

      - name: Create artifact zip
        run: cd dist/${{ env.APP_NAME }}/browser && zip ../${{ env.ARTIFACT_FILE_NAME }} *

      - uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: dist/${{ env.ARTIFACT_FILE_NAME }}
  Deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1
      AWS_DEFAULT_OUTPUT: json
      S3_URL:
      AMPLIFY_DEPLOYMENT_JOB_ID:
      AMPLIFY_DEPLOY_ENV:

    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Upload to s3
        run: aws s3 cp ${{ env.ARTIFACT_FILE_NAME }} ${{ env.ARTIFACT_S3_PATH }}

      - name: Retrieve s3 url
        run: s3url=$(aws s3 presign ${{ env.ARTIFACT_S3_PATH }} --expires-in 120) && echo "S3_URL=$s3url" >> $GITHUB_ENV
      
      - name: Set env
        run: |
          if [[ $BRANCH == 'main' ]]; then
              echo "AMPLIFY_DEPLOY_ENV=dev" >> "$GITHUB_ENV"
          elif [[ $BRANCH == 'release' ]]; then
              echo "AMPLIFY_DEPLOY_ENV=prod" >> "$GITHUB_ENV"
          fi

      - name: Trigger amplify deployment
        run: jobId=$(aws amplify start-deployment --app-id ${{ env.APP_ID }} --branch-name dev --source-url '${{ env.S3_URL }}' --query 'jobSummary.jobId') && echo "AMPLIFY_DEPLOYMENT_JOB_ID=$jobId" >> $GITHUB_ENV
